version: '3.9'

services:
  app:
    image: sales-api-rest
    build:
      context: .
      dockerfile: SalesAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    networks:
      - ploomes-test

networks:
  ploomes-test:
    driver: bridge
